[package]
name = "lox_bytecode_vm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.27", features = ["derive"]}
rustc-hash = "2.1.1"

[dev-dependencies]
regex = "1.11.1"
test-generator = "0.3.1"
criterion = "0.6"

[[bench]]
name = "benchmark"
harness = false
